env_settings:
  sumo_start_config: ["sumo-gui", "-c", "./4RL-test/simple6nodes.sumocfg", '--start']
  sumo_start_config_cmd: ["sumo", "-c", "./4RL-test/simple6nodes.sumocfg", '--start']
  pre_steps: 10
  simulation_time: 1000
deep_learning_settings:
  